# -*- mode: ruby -*-
# vi: set ft=ruby :
# Default Vagrantfile
# Contains defaults for all systems.

VAGRANTFILE_API_VERSION ||= "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.customize ["modifyvm", :id, "--usb", "off"]
    v.customize ["modifyvm", :id, "--usbehci", "off"]
  end

  begin
    unless `ipconfig | grep -A3 "Ethernet adapter Local Area Connection"`.include?("Media disconnected")
      config.vm.network "public_network", :bridge => 'Intel(R) Ethernet Connection I218-LM'
    end
  rescue Exception => e
    puts "Failed to determine and set ethernet adapter configuration!\n#{e}"
  end
  #config.vm.network "public_network", :bridge => 'Intel(R) Ethernet Connection I218-LM'
  
  config.omnibus.chef_version = :latest
  
  # config.vm.synced_folder ".", "/vagrant", disabled: true
end
